# Generated by Django 5.0.1 on 2024-01-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="auctionslist",
            name="listed_by",
            field=models.CharField(default="Admin", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auctionslist",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="auctions/auction_img/"
            ),
        ),
    ]
