# Generated by Django 5.0.1 on 2024-01-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_bid_auctionslist_listed_by_alter_auctionslist_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionslist",
            name="Bid",
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bid",
            name="price",
            field=models.IntegerField(max_length=10),
        ),
    ]
