# Generated by Django 5.0.1 on 2024-01-28 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_auctionslist_bid_alter_bid_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionslist",
            old_name="Bid",
            new_name="bid",
        ),
    ]
