# Generated by Django 5.0.1 on 2024-01-28 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_rename_bid_auctionslist_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="auction",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.auctionslist",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="bid_by",
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auctionslist",
            name="bid",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="bid",
            name="price",
            field=models.IntegerField(),
        ),
    ]
