# Generated by Django 5.0.1 on 2024-01-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_bid_auction_bid_bid_by_alter_auctionslist_bid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="bid_by",
        ),
        migrations.AddField(
            model_name="auctionslist",
            name="winner",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
