# Generated by Django 5.0.1 on 2024-01-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_remove_bid_bid_by_auctionslist_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionslist",
            name="close",
            field=models.BooleanField(default=False),
        ),
    ]
