# Generated by Django 5.0.1 on 2024-01-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="username",
            field=models.CharField(default="Admin", max_length=64),
            preserve_default=False,
        ),
    ]
