# Generated by Django 5.0.1 on 2024-01-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_comments_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionslist",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="auctions/auction_img/"
            ),
        ),
    ]
